#!/usr/bin/env python3
##
## EPITECH PROJECT, 2020
## 107transfer
## File description:
## maths python
##

import sys

import error
import function


def main():
    if "-h" in sys.argv or "--help" in sys.argv:
        error.usage()
        return 0
    error.all_error(len(sys.argv))
    num = function.func_in_tab(1)
    den = function.func_in_tab(2)
    function.func_calc(num, den)
    return 0


if __name__ == "__main__":
    main()
